In [1]:
import shekel

q = shekel.Shekel(m=5)

q.xmin

In [2]:
q.xmin

[array([4., 4., 4., 4.]),
 array([1., 1., 1., 1.]),
 array([8., 8., 8., 8.]),
 array([6., 6., 6., 6.])]

In [2]:
e = q.make_explicit()

In [4]:
e.f(e.xmin[0])

In [5]:
1/0.1

In [6]:
e.xmin[0]

In [7]:
e.c[0]

AttributeError: 'Shekel' object has no attribute 'c'

In [21]:
import numpy as np

a = np.array([[4,4,4,4],
             [1,1,1,1],
             [8,8,8,8],
             [6,6,6,6],
             [3,7,3,7]])
c = np.array([0.1, 0.2, 0.2, 0.4, 0.4])

x = np.array(e.xmin[0])

def f(x):
    return -sum( [ (np.dot(x-a[i], x-a[i]) + c[i])**-1 for i in range(5) ])


f(a[1])

In [22]:
Piecewise

NameError: name 'Piecewise' is not defined

In [23]:
Idx

NameError: name 'Idx' is not defined

In [24]:
from sympy import *

In [41]:
y = symbols('y')
Piecewise(
(1, And(LessThan(y,0),True)),
    (2,True)
)

⎧1  for y ≤ 0
⎨            
⎩2  otherwise

In [56]:
a, k, m = symbols('a k m')

x = IndexedBase('x')
i = Idx('i')

u = Piecewise(
(k*(x[i]-a)**m, x[i] > a),
(0, And( GreaterThan(x[i],-a), LessThan(x[i],a))
))

u

⎧             m               
⎪k⋅(-a + x[i])   for a < x[i] 
⎨                             
⎪      0         for a ≥ -x[i]
⎩                             

In [31]:
a